package Util;

import java.util.regex.Pattern;

public class Constant {
    //TODO replace it with your DB credentials
    static public String DBUserName = "root";
    static public String DBPassword = "root";

    static public Pattern namePattern = Pattern.compile("^[ A-Za-z]+$");
    static public Pattern emailPattern = Pattern.compile("^[a-zA-Z0-9_+&*-]+(?:\\."
            + "[a-zA-Z0-9_+&*-]+)*@"
            + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
            + "A-Z]{2,7}$");
    
    static public String jsonn = "[\n"
    		+ "	{\n"
    		+ "	    \"id\": \"SLxKy00itrk-ta8r8zCzTA\",\n"
    		+ "	    \"alias\": \"easy-street-burgers-los-angeles\",\n"
    		+ "	    \"name\": \"Easy Street Burgers\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/kkJ9A3hFzwOPLYHxqkrrrQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/easy-street-burgers-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 206,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.088796,\n"
    		+ "	        \"longitude\": -118.308573\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"1000 N Western Ave\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90029\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"1000 N Western Ave\",\n"
    		+ "	            \"Los Angeles, CA 90029\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+18189663009\",\n"
    		+ "	    \"display_phone\": \"(818) 966-3009\",\n"
    		+ "	    \"distance\": 3247.065962603458\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"4JZK5nkIP6vKXdWNK8qXEg\",\n"
    		+ "	    \"alias\": \"burger-she-wrote-los-angeles-2\",\n"
    		+ "	    \"name\": \"Burger She Wrote\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/SJL9BlKsKXOiUaOcGCwObg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/burger-she-wrote-los-angeles-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 60,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.0760151,\n"
    		+ "	        \"longitude\": -118.35244\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"7454 1/2 Beverly Blvd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90036\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"7454 1/2 Beverly Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90036\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13232723474\",\n"
    		+ "	    \"display_phone\": \"(323) 272-3474\",\n"
    		+ "	    \"distance\": 3280.4709120709385\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"XlWFM7ut_TFH0TzwcdPzkQ\",\n"
    		+ "	    \"alias\": \"the-win-dow-venice-boardwalk-los-angeles-3\",\n"
    		+ "	    \"name\": \"The Win-Dow - Venice Boardwalk\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/OLOryiaNNtWbZmgpTCJnLg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/the-win-dow-venice-boardwalk-los-angeles-3?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 111,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 33.9854236,\n"
    		+ "	        \"longitude\": -118.4722854\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"1827 Ocean Front Walk\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90291\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"1827 Ocean Front Walk\",\n"
    		+ "	            \"Los Angeles, CA 90291\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+14242594834\",\n"
    		+ "	    \"display_phone\": \"(424) 259-4834\",\n"
    		+ "	    \"distance\": 16283.120449246555\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"aOvUcX4sZEm8BYDkp_561w\",\n"
    		+ "	    \"alias\": \"chris-n-eddy-s-los-angeles\",\n"
    		+ "	    \"name\": \"Chris N’ Eddy’s\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/sz-wTODk_N7cAKiRwdcdNA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/chris-n-eddy-s-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 126,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.0983925,\n"
    		+ "	        \"longitude\": -118.3107247\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"5539 Sunset Blvd\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90028\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"5539 Sunset Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90028\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13235443600\",\n"
    		+ "	    \"display_phone\": \"(323) 544-3600\",\n"
    		+ "	    \"distance\": 4208.327080846563\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"DJek3FUewBzMc0gS-Gms9w\",\n"
    		+ "	    \"alias\": \"morrison-atwater-village-los-angeles\",\n"
    		+ "	    \"name\": \"Morrison Atwater Village\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/rSDJYD7foVFKvk0Dy6SzzQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/morrison-atwater-village-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 5088,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"gastropubs\",\n"
    		+ "	            \"title\": \"Gastropubs\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"salad\",\n"
    		+ "	            \"title\": \"Salad\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.12384,\n"
    		+ "	        \"longitude\": -118.26868\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"3179 Los Feliz Blvd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90039\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"3179 Los Feliz Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90039\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13236671839\",\n"
    		+ "	    \"display_phone\": \"(323) 667-1839\",\n"
    		+ "	    \"distance\": 8445.157607209154\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"3_K8UCyMkLiDH4SwaLPylQ\",\n"
    		+ "	    \"alias\": \"blasteran-beverly-hills\",\n"
    		+ "	    \"name\": \"Blasteran\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/cPKA2KCMiCmO8cvLeNFiGw/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/blasteran-beverly-hills?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 330,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"newamerican\",\n"
    		+ "	            \"title\": \"American (New)\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"asianfusion\",\n"
    		+ "	            \"title\": \"Asian Fusion\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 5.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.063192,\n"
    		+ "	        \"longitude\": -118.375939\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"restaurant_reservation\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"272 South La Cienega Blvd\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Beverly Hills\",\n"
    		+ "	        \"zip_code\": \"90211\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"272 South La Cienega Blvd\",\n"
    		+ "	            \"Beverly Hills, CA 90211\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+14242743611\",\n"
    		+ "	    \"display_phone\": \"(424) 274-3611\",\n"
    		+ "	    \"distance\": 5028.907294462858\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"XHTsPRgT9UNBi_iZ15nFmw\",\n"
    		+ "	    \"alias\": \"blue-bird-burgers-los-angeles\",\n"
    		+ "	    \"name\": \"Blue Bird Burgers\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/bi-SzjgZF0jjlcN2ZRu9yg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/blue-bird-burgers-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 68,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"chicken_wings\",\n"
    		+ "	            \"title\": \"Chicken Wings\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"sandwiches\",\n"
    		+ "	            \"title\": \"Sandwiches\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 5.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.06918,\n"
    		+ "	        \"longitude\": -118.29441\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"3601 W 3rd St\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90020\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"3601 W 3rd St\",\n"
    		+ "	            \"Los Angeles, CA 90020\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12133185535\",\n"
    		+ "	    \"display_phone\": \"(213) 318-5535\",\n"
    		+ "	    \"distance\": 2630.695918151583\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"Q3pwRtT8v8oTCKFEYJgCbg\",\n"
    		+ "	    \"alias\": \"cassells-hamburgers-los-angeles-2\",\n"
    		+ "	    \"name\": \"Cassell's Hamburgers\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/bFM8O7BGe8eqcp8F8cMkOQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/cassells-hamburgers-los-angeles-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 1688,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.06333,\n"
    		+ "	        \"longitude\": -118.30072\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"3600 W 6th St\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90020\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"3600 W 6th St\",\n"
    		+ "	            \"Los Angeles, CA 90020\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12133875502\",\n"
    		+ "	    \"display_phone\": \"(213) 387-5502\",\n"
    		+ "	    \"distance\": 1928.6983368720612\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"esdnaTuF0U9JGU447A0yvQ\",\n"
    		+ "	    \"alias\": \"goldburger-los-angeles\",\n"
    		+ "	    \"name\": \"Goldburger\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/CYB8wYotfmQwjGdxRFVd2g/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/goldburger-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 234,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"desserts\",\n"
    		+ "	            \"title\": \"Desserts\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.1194678,\n"
    		+ "	        \"longitude\": -118.1958786\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"5623 York Blvd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90042\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"5623 York Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90042\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"\",\n"
    		+ "	    \"display_phone\": \"\",\n"
    		+ "	    \"distance\": 13228.137906182159\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"g1RqknBKd1r1ajHW8xhAkQ\",\n"
    		+ "	    \"alias\": \"hollywood-burger-los-angeles\",\n"
    		+ "	    \"name\": \"Hollywood Burger\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/Rh0RGoUrG4FrfWF2MXvt5A/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/hollywood-burger-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 701,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.10145472844192,\n"
    		+ "	        \"longitude\": -118.32601257150795\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"6250 Hollywood Blvd\",\n"
    		+ "	        \"address2\": \"Ste 100\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90028\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"6250 Hollywood Blvd\",\n"
    		+ "	            \"Ste 100\",\n"
    		+ "	            \"Los Angeles, CA 90028\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13233785668\",\n"
    		+ "	    \"display_phone\": \"(323) 378-5668\",\n"
    		+ "	    \"distance\": 4453.279969325831\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"26fIBSlQkaTa29uoKAvZOw\",\n"
    		+ "	    \"alias\": \"burgers-never-say-die-los-angeles-2\",\n"
    		+ "	    \"name\": \"Burgers Never Say Die\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/B-KMybddnREZTdFkd0urkQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/burgers-never-say-die-los-angeles-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 865,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.09985641,\n"
    		+ "	        \"longitude\": -118.25892958\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"2388 Glendale Blvd\",\n"
    		+ "	        \"address2\": \"Unit A\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90039\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"2388 Glendale Blvd\",\n"
    		+ "	            \"Unit A\",\n"
    		+ "	            \"Los Angeles, CA 90039\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13239226161\",\n"
    		+ "	    \"display_phone\": \"(323) 922-6161\",\n"
    		+ "	    \"distance\": 7154.440369932181\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"rMPUk3S0KppytGvrsqmQ8g\",\n"
    		+ "	    \"alias\": \"the-fix-burger-los-angeles\",\n"
    		+ "	    \"name\": \"The Fix Burger\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/V4XaE2Ms6Na9BlZb07ymIg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/the-fix-burger-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 762,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.1048199,\n"
    		+ "	        \"longitude\": -118.27272\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"2520 Hyperion Ave\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90027\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"2520 Hyperion Ave\",\n"
    		+ "	            \"Los Angeles, CA 90027\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13236618494\",\n"
    		+ "	    \"display_phone\": \"(323) 661-8494\",\n"
    		+ "	    \"distance\": 6561.684295413282\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"6U55z4ejutsNYh7jAdWdwA\",\n"
    		+ "	    \"alias\": \"black-sheep-burgers-los-angeles\",\n"
    		+ "	    \"name\": \"Black Sheep Burgers\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/wZy9nLQvmDmV-zO6SHddpQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/black-sheep-burgers-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 513,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"salad\",\n"
    		+ "	            \"title\": \"Salad\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"sandwiches\",\n"
    		+ "	            \"title\": \"Sandwiches\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.039413,\n"
    		+ "	        \"longitude\": -118.442961\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"11313 Mississippi Ave\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90025\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"11313 Mississippi Ave\",\n"
    		+ "	            \"Los Angeles, CA 90025\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+14243729210\",\n"
    		+ "	    \"display_phone\": \"(424) 372-9210\",\n"
    		+ "	    \"distance\": 11469.29646322527\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"Nm1iV8Aaat4EF_0hPevXhg\",\n"
    		+ "	    \"alias\": \"burgershop-los-angeles-2\",\n"
    		+ "	    \"name\": \"BurgerShop\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/6WGQmaFIgkZFyUI-pCVoPg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/burgershop-los-angeles-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 121,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"hotdogs\",\n"
    		+ "	            \"title\": \"Fast Food\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.04384,\n"
    		+ "	        \"longitude\": -118.25268\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"724 S Spring St\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90014\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"724 S Spring St\",\n"
    		+ "	            \"Los Angeles, CA 90014\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12132676993\",\n"
    		+ "	    \"display_phone\": \"(213) 267-6993\",\n"
    		+ "	    \"distance\": 6638.311713679442\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"sYn3SNQP-j2t2XSwjlCbRg\",\n"
    		+ "	    \"alias\": \"montys-good-burger-los-angeles\",\n"
    		+ "	    \"name\": \"Monty's Good Burger\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/NaDjAGKMS7KhTX9dYMo7_Q/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/montys-good-burger-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 2268,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"vegan\",\n"
    		+ "	            \"title\": \"Vegan\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"chickenshop\",\n"
    		+ "	            \"title\": \"Chicken Shop\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.06469,\n"
    		+ "	        \"longitude\": -118.30876\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"516 S Western Ave\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90020\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"516 S Western Ave\",\n"
    		+ "	            \"Los Angeles, CA 90020\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12139150257\",\n"
    		+ "	    \"display_phone\": \"(213) 915-0257\",\n"
    		+ "	    \"distance\": 1206.4348071176648\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"fETqhZO6YjM1VTWCJpT8VA\",\n"
    		+ "	    \"alias\": \"lowboy-los-angeles-3\",\n"
    		+ "	    \"name\": \"Lowboy\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/u0yXHX2POsdWZBtZQ0G_nQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/lowboy-los-angeles-3?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 191,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"cocktailbars\",\n"
    		+ "	            \"title\": \"Cocktail Bars\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.0763248,\n"
    		+ "	        \"longitude\": -118.2567306\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"1540 Sunset Blvd\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90026\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"1540 Sunset Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90026\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12132668161\",\n"
    		+ "	    \"display_phone\": \"(213) 266-8161\",\n"
    		+ "	    \"distance\": 6171.268232244014\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"oMWttbTso0Mh_aIDIAFToQ\",\n"
    		+ "	    \"alias\": \"amboy-los-angeles\",\n"
    		+ "	    \"name\": \"Amboy\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/p3iW3c0qvoRLNuBfSolqJg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/amboy-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 174,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"steak\",\n"
    		+ "	            \"title\": \"Steakhouses\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.061351,\n"
    		+ "	        \"longitude\": -118.239349\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"727 N Broadway\",\n"
    		+ "	        \"address2\": \"Ste 117\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90042\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"727 N Broadway\",\n"
    		+ "	            \"Ste 117\",\n"
    		+ "	            \"Los Angeles, CA 90042\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12139358188\",\n"
    		+ "	    \"display_phone\": \"(213) 935-8188\",\n"
    		+ "	    \"distance\": 7556.627065100168\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"JFA49Hzbgw0E5FdQ3UFOew\",\n"
    		+ "	    \"alias\": \"love-hour-los-angeles-2\",\n"
    		+ "	    \"name\": \"Love Hour\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/NDNUj3Un0qS8xp6Do5Yamg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/love-hour-los-angeles-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 33,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"foodstands\",\n"
    		+ "	            \"title\": \"Food Stands\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 5.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.0643899867372,\n"
    		+ "	        \"longitude\": -118.308910019696\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"532 S Western Ave\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90020\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"532 S Western Ave\",\n"
    		+ "	            \"Los Angeles, CA 90020\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"\",\n"
    		+ "	    \"display_phone\": \"\",\n"
    		+ "	    \"distance\": 1190.2019618168376\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"71W-QN3-_DHnzUkAc7EG6Q\",\n"
    		+ "	    \"alias\": \"stout-burgers-and-beers-los-angeles\",\n"
    		+ "	    \"name\": \"Stout Burgers & Beers\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/k2lUZAeuAgqvfkpS5FxT5Q/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/stout-burgers-and-beers-los-angeles?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 2199,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"gastropubs\",\n"
    		+ "	            \"title\": \"Gastropubs\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.09942,\n"
    		+ "	        \"longitude\": -118.32934\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"1544 N Cahuenga Blvd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90028\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"1544 N Cahuenga Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90028\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+13234693801\",\n"
    		+ "	    \"display_phone\": \"(323) 469-3801\",\n"
    		+ "	    \"distance\": 4276.269947958211\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"mZgFVO_0xoB2US8KPzIKiA\",\n"
    		+ "	    \"alias\": \"burger-bitch-los-angeles-4\",\n"
    		+ "	    \"name\": \"Burger Bitch\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/w2o2MI7cw4Vg-gYFguseKQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/burger-bitch-los-angeles-4?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 56,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"divebars\",\n"
    		+ "	            \"title\": \"Dive Bars\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"cocktailbars\",\n"
    		+ "	            \"title\": \"Cocktail Bars\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 34.03468,\n"
    		+ "	        \"longitude\": -118.43933\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [\n"
    		+ "	        \"delivery\",\n"
    		+ "	        \"pickup\"\n"
    		+ "	    ],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"11326 W Pico Blvd\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Los Angeles\",\n"
    		+ "	        \"zip_code\": \"90064\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"11326 W Pico Blvd\",\n"
    		+ "	            \"Los Angeles, CA 90064\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+18443644120\",\n"
    		+ "	    \"display_phone\": \"(844) 364-4120\",\n"
    		+ "	    \"distance\": 11263.080771846146\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"hgZUMSrhohHkGKeCEiiy-A\",\n"
    		+ "	    \"alias\": \"south-gate-brewing-company-oakhurst-4\",\n"
    		+ "	    \"name\": \"South Gate Brewing Company\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/Po-Q8jwK0-W5HyKDsYd4tg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/south-gate-brewing-company-oakhurst-4?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 1256,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"brewpubs\",\n"
    		+ "	            \"title\": \"Brewpubs\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tapasmallplates\",\n"
    		+ "	            \"title\": \"Tapas/Small Plates\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.3331104,\n"
    		+ "	        \"longitude\": -119.660292\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40233 Enterprise Dr\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40233 Enterprise Dr\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596922739\",\n"
    		+ "	    \"display_phone\": \"(559) 692-2739\",\n"
    		+ "	    \"distance\": 32190.468670098337\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"GPP5E-f1dzAN08jNogYCjw\",\n"
    		+ "	    \"alias\": \"smokehouse-41-oakhurst\",\n"
    		+ "	    \"name\": \"Smokehouse 41\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/7g1UzP5t7h-6bQ3j2DsWFg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/smokehouse-41-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 460,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"bbq\",\n"
    		+ "	            \"title\": \"Barbeque\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"smokehouse\",\n"
    		+ "	            \"title\": \"Smokehouse\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"sandwiches\",\n"
    		+ "	            \"title\": \"Sandwiches\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.33914,\n"
    		+ "	        \"longitude\": -119.64334\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40713 Hwy 41\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40713 Hwy 41\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596422271\",\n"
    		+ "	    \"display_phone\": \"(559) 642-2271\",\n"
    		+ "	    \"distance\": 30931.491762242607\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"Ty4hB9Gez3uD4eSbfYPnAQ\",\n"
    		+ "	    \"alias\": \"the-cool-bean-cafe-oakhurst\",\n"
    		+ "	    \"name\": \"The Cool Bean Cafe\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/LegdHa-goov360bsoASYug/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/the-cool-bean-cafe-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 325,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"coffee\",\n"
    		+ "	            \"title\": \"Coffee & Tea\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.33215,\n"
    		+ "	        \"longitude\": -119.65455\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40120 Hwy 41\",\n"
    		+ "	        \"address2\": \"Ste C\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40120 Hwy 41\",\n"
    		+ "	            \"Ste C\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596837575\",\n"
    		+ "	    \"display_phone\": \"(559) 683-7575\",\n"
    		+ "	    \"distance\": 31699.20874012438\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"JVsvjCZhSlImlVseRnPQZg\",\n"
    		+ "	    \"alias\": \"plazuelas-mexican-restaurant-and-taqueria-oakhurst\",\n"
    		+ "	    \"name\": \"Plazuelas Mexican Restaurant & Taqueria\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/Y2c0WqhmYhPy2zxzBAT09A/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/plazuelas-mexican-restaurant-and-taqueria-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 565,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"mexican\",\n"
    		+ "	            \"title\": \"Mexican\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"beerbar\",\n"
    		+ "	            \"title\": \"Beer Bar\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.331555,\n"
    		+ "	        \"longitude\": -119.6563089\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40015 Hwy 49\",\n"
    		+ "	        \"address2\": \"Ste 203 & 204\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40015 Hwy 49\",\n"
    		+ "	            \"Ste 203 & 204\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596587771\",\n"
    		+ "	    \"display_phone\": \"(559) 658-7771\",\n"
    		+ "	    \"distance\": 31804.622452758053\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"5dejzAItnpvuLTtsqN_APg\",\n"
    		+ "	    \"alias\": \"casa-velasco-mexican-restaurant-bass-lake\",\n"
    		+ "	    \"name\": \"Casa Velasco Mexican Restaurant\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/9LjSrt8G5Trn03fLLq5fVA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/casa-velasco-mexican-restaurant-bass-lake?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 205,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"mexican\",\n"
    		+ "	            \"title\": \"Mexican\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.32073,\n"
    		+ "	        \"longitude\": -119.5586\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"54311 Rd 432\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Bass Lake\",\n"
    		+ "	        \"zip_code\": \"93604\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"54311 Rd 432\",\n"
    		+ "	            \"Bass Lake, CA 93604\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596832272\",\n"
    		+ "	    \"display_phone\": \"(559) 683-2272\",\n"
    		+ "	    \"distance\": 23106.11349536631\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"8rmEBlB0_qBSy0P3u-kWjw\",\n"
    		+ "	    \"alias\": \"wild-fig-kitchen-coarsegold-5\",\n"
    		+ "	    \"name\": \"Wild Fig Kitchen\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/lhE1D8gO2J6ohIBy7npnvQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/wild-fig-kitchen-coarsegold-5?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 283,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"sandwiches\",\n"
    		+ "	            \"title\": \"Sandwiches\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.2622980132899,\n"
    		+ "	        \"longitude\": -119.700374975394\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"35300 Hwy 41\",\n"
    		+ "	        \"address2\": \"Ste 110\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Coarsegold\",\n"
    		+ "	        \"zip_code\": \"93614\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"35300 Hwy 41\",\n"
    		+ "	            \"Ste 110\",\n"
    		+ "	            \"Coarsegold, CA 93614\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596583447\",\n"
    		+ "	    \"display_phone\": \"(559) 658-3447\",\n"
    		+ "	    \"distance\": 34900.81718068726\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"gwANdrsPZr3ZVAqN52vwqg\",\n"
    		+ "	    \"alias\": \"the-elderberry-house-oakhurst\",\n"
    		+ "	    \"name\": \"The Elderberry House\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/7adut7tTEVDY972A-EcTJQ/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/the-elderberry-house-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 231,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"french\",\n"
    		+ "	            \"title\": \"French\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.327100397143525,\n"
    		+ "	        \"longitude\": -119.66091834110446\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"48688 Victoria Ln\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"48688 Victoria Ln\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596836800\",\n"
    		+ "	    \"display_phone\": \"(559) 683-6800\",\n"
    		+ "	    \"distance\": 32099.466229333673\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"M6qUGNq8_25RUs8Q9KcLaQ\",\n"
    		+ "	    \"alias\": \"duceys-on-the-lake-bass-lake-2\",\n"
    		+ "	    \"name\": \"Ducey's on the Lake\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/ht5jtZwkBNxPV0ryJLWTkA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/duceys-on-the-lake-bass-lake-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 469,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"seafood\",\n"
    		+ "	            \"title\": \"Seafood\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"steak\",\n"
    		+ "	            \"title\": \"Steakhouses\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 3.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.3189103,\n"
    		+ "	        \"longitude\": -119.5570908\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"39255 Marina Dr\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Bass Lake\",\n"
    		+ "	        \"zip_code\": \"93604\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"39255 Marina Dr\",\n"
    		+ "	            \"Bass Lake, CA 93604\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596423131\",\n"
    		+ "	    \"display_phone\": \"(559) 642-3131\",\n"
    		+ "	    \"distance\": 22956.019078436006\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"Vowoq0eFObqqYkdzQ-zBAQ\",\n"
    		+ "	    \"alias\": \"shaver-lake-pizza-shaver-lake\",\n"
    		+ "	    \"name\": \"Shaver Lake Pizza\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/4ZluF9XYHlOybHgWJnSEwg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/shaver-lake-pizza-shaver-lake?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 316,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"pizza\",\n"
    		+ "	            \"title\": \"Pizza\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 3.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.1074244,\n"
    		+ "	        \"longitude\": -119.3191947\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"41820 Tollhouse Rd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Shaver Lake\",\n"
    		+ "	        \"zip_code\": \"93664\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"41820 Tollhouse Rd\",\n"
    		+ "	            \"Shaver Lake, CA 93664\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15598417249\",\n"
    		+ "	    \"display_phone\": \"(559) 841-7249\",\n"
    		+ "	    \"distance\": 17759.41573918924\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"-3A2-voqIBSQEbrupcbw5g\",\n"
    		+ "	    \"alias\": \"petes-place-oakhurst\",\n"
    		+ "	    \"name\": \"Pete's Place\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/b6i_yXPoGGqGkD9mz0jkRg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/petes-place-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 404,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.33106,\n"
    		+ "	        \"longitude\": -119.65481\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40093 Hwy 41\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40093 Hwy 41\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596830772\",\n"
    		+ "	    \"display_phone\": \"(559) 683-0772\",\n"
    		+ "	    \"distance\": 31684.13068965148\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"byUUxQV1CSOqJ4aFklMVrA\",\n"
    		+ "	    \"alias\": \"yosemite-national-park-yosemite-national-park-11\",\n"
    		+ "	    \"name\": \"Yosemite National Park\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/cCgZvrU8qSWzcG0MGNXJAg/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/yosemite-national-park-yosemite-national-park-11?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 1195,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"parks\",\n"
    		+ "	            \"title\": \"Parks\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"campgrounds\",\n"
    		+ "	            \"title\": \"Campgrounds\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"hiking\",\n"
    		+ "	            \"title\": \"Hiking\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.747525,\n"
    		+ "	        \"longitude\": -119.585552\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": null,\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": null,\n"
    		+ "	        \"city\": \"Yosemite National Park\",\n"
    		+ "	        \"zip_code\": \"95389\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"Yosemite National Park, CA 95389\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+12093720200\",\n"
    		+ "	    \"display_phone\": \"(209) 372-0200\",\n"
    		+ "	    \"distance\": 58863.77059998652\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"O2fh-ejsJJc98fGJlrxiVA\",\n"
    		+ "	    \"alias\": \"huntington-lake-lakeshore\",\n"
    		+ "	    \"name\": \"Huntington Lake\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/YOM6q9dD4GG7IdgeexTO5A/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/huntington-lake-lakeshore?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 30,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"lakes\",\n"
    		+ "	            \"title\": \"Lakes\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.2554330018814,\n"
    		+ "	        \"longitude\": -119.161609075963\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"Lake Huntington Rd Toll House Rd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Lakeshore\",\n"
    		+ "	        \"zip_code\": \"93634\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"Lake Huntington Rd Toll House Rd\",\n"
    		+ "	            \"Lakeshore, CA 93634\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15592970706\",\n"
    		+ "	    \"display_phone\": \"(559) 297-0706\",\n"
    		+ "	    \"distance\": 12843.651643124414\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"_uItnZWBDKXCtNeRXo0kUg\",\n"
    		+ "	    \"alias\": \"reimers-candies-and-gifts-oakhurst-2\",\n"
    		+ "	    \"name\": \"Reimer's Candies & Gifts\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/l42zVRBxsN6cqRqHejrzRA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/reimers-candies-and-gifts-oakhurst-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 128,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"icecream\",\n"
    		+ "	            \"title\": \"Ice Cream & Frozen Yogurt\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"candy\",\n"
    		+ "	            \"title\": \"Candy Stores\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.3594409,\n"
    		+ "	        \"longitude\": -119.644062\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"41969 Hwy 41\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"41969 Hwy 41\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596423232\",\n"
    		+ "	    \"display_phone\": \"(559) 642-3232\",\n"
    		+ "	    \"distance\": 31618.596388213788\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"g2o1HKG93CobV_mn2sO8aQ\",\n"
    		+ "	    \"alias\": \"hungry-hut-shaver-lake\",\n"
    		+ "	    \"name\": \"Hungry Hut\",\n"
    		+ "	    \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/TuPjQTVLZdPE93XugasBQw/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/hungry-hut-shaver-lake?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 295,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"burgers\",\n"
    		+ "	            \"title\": \"Burgers\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"sandwiches\",\n"
    		+ "	            \"title\": \"Sandwiches\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 3.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.1093496,\n"
    		+ "	        \"longitude\": -119.3194913\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"42008 Tollhouse Rd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Shaver Lake\",\n"
    		+ "	        \"zip_code\": \"93664\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"42008 Tollhouse Rd\",\n"
    		+ "	            \"Shaver Lake, CA 93664\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15598413222\",\n"
    		+ "	    \"display_phone\": \"(559) 841-3222\",\n"
    		+ "	    \"distance\": 17548.957048117296\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"0agq0wMl5TAyH4fSxN8NUA\",\n"
    		+ "	    \"alias\": \"skadi-mammoth-lakes-2\",\n"
    		+ "	    \"name\": \"SKADI\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/EE8FLJhwYbg9T-mbMjHWqw/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/skadi-mammoth-lakes-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 360,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"modern_european\",\n"
    		+ "	            \"title\": \"Modern European\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"wine_bars\",\n"
    		+ "	            \"title\": \"Wine Bars\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 5.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.6512,\n"
    		+ "	        \"longitude\": -118.9829\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"94 Berner St\",\n"
    		+ "	        \"address2\": \"Ste A\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Mammoth Lakes\",\n"
    		+ "	        \"zip_code\": \"93546\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"94 Berner St\",\n"
    		+ "	            \"Ste A\",\n"
    		+ "	            \"Mammoth Lakes, CA 93546\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+17609140962\",\n"
    		+ "	    \"display_phone\": \"(760) 914-0962\",\n"
    		+ "	    \"distance\": 51372.09146095\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"QXCnHYK0fnWA9HsSXEJP6w\",\n"
    		+ "	    \"alias\": \"black-velvet-coffee-mammoth-lakes\",\n"
    		+ "	    \"name\": \"Black Velvet Coffee\",\n"
    		+ "	    \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/YdPL4weY6DaNm4Ch63WHAA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/black-velvet-coffee-mammoth-lakes?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 715,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"coffee\",\n"
    		+ "	            \"title\": \"Coffee & Tea\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"beerbar\",\n"
    		+ "	            \"title\": \"Beer Bar\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"wine_bars\",\n"
    		+ "	            \"title\": \"Wine Bars\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.6477099,\n"
    		+ "	        \"longitude\": -118.97161\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"3343 Main St\",\n"
    		+ "	        \"address2\": \"Ste F\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Mammoth Lakes\",\n"
    		+ "	        \"zip_code\": \"93546\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"3343 Main St\",\n"
    		+ "	            \"Ste F\",\n"
    		+ "	            \"Mammoth Lakes, CA 93546\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"\",\n"
    		+ "	    \"display_phone\": \"\",\n"
    		+ "	    \"distance\": 51598.003486034955\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"bBLeD88rg-05Kq4zxVammA\",\n"
    		+ "	    \"alias\": \"shaver-lake-pub-n-grub-shaver-lake\",\n"
    		+ "	    \"name\": \"Shaver Lake Pub N Grub\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/IXl6PwAT6x-mICNS8ODdfA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/shaver-lake-pub-n-grub-shaver-lake?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 144,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"pubs\",\n"
    		+ "	            \"title\": \"Pubs\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"tradamerican\",\n"
    		+ "	            \"title\": \"American (Traditional)\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.1075958172791,\n"
    		+ "	        \"longitude\": -119.318211860955\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"41782 Dorabella Rd\",\n"
    		+ "	        \"address2\": null,\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Shaver Lake\",\n"
    		+ "	        \"zip_code\": \"93664\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"41782 Dorabella Rd\",\n"
    		+ "	            \"Shaver Lake, CA 93664\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15598414411\",\n"
    		+ "	    \"display_phone\": \"(559) 841-4411\",\n"
    		+ "	    \"distance\": 17738.47103966455\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"ApH6hiYN3RCLXHpqLUIOrA\",\n"
    		+ "	    \"alias\": \"the-stove-restaurant-mammoth-lakes\",\n"
    		+ "	    \"name\": \"The Stove Restaurant\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/zmCRfad94i9wtfIEGmrR1w/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/the-stove-restaurant-mammoth-lakes?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 986,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"breakfast_brunch\",\n"
    		+ "	            \"title\": \"Breakfast & Brunch\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"newamerican\",\n"
    		+ "	            \"title\": \"American (New)\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.63669,\n"
    		+ "	        \"longitude\": -118.96669\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"644 Old Mammoth Rd\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Mammoth Lakes\",\n"
    		+ "	        \"zip_code\": \"93546\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"644 Old Mammoth Rd\",\n"
    		+ "	            \"Mammoth Lakes, CA 93546\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+17609342821\",\n"
    		+ "	    \"display_phone\": \"(760) 934-2821\",\n"
    		+ "	    \"distance\": 50877.84082515914\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"-VGZEH8aSwWv1nYDUrNTew\",\n"
    		+ "	    \"alias\": \"el-cid-mexican-cuisine-oakhurst-2\",\n"
    		+ "	    \"name\": \"El Cid Mexican Cuisine\",\n"
    		+ "	    \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/BJSPRH4XnzstEhC-1l23KA/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/el-cid-mexican-cuisine-oakhurst-2?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 424,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"mexican\",\n"
    		+ "	            \"title\": \"Mexican\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 3.5,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.358658,\n"
    		+ "	        \"longitude\": -119.644107\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"41939 Hwy 41\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"41939 Hwy 41\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596836668\",\n"
    		+ "	    \"display_phone\": \"(559) 683-6668\",\n"
    		+ "	    \"distance\": 31594.2633197927\n"
    		+ "	},\n"
    		+ "	{\n"
    		+ "	    \"id\": \"A_7HXAZmYEEQDe8mk27urA\",\n"
    		+ "	    \"alias\": \"oakhurst-grill-and-whiskey-41-lounge-oakhurst\",\n"
    		+ "	    \"name\": \"Oakhurst Grill and Whiskey 41 Lounge\",\n"
    		+ "	    \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/OU2RX5W552gegriHAyPd1g/o.jpg\",\n"
    		+ "	    \"is_closed\": false,\n"
    		+ "	    \"url\": \"https://www.yelp.com/biz/oakhurst-grill-and-whiskey-41-lounge-oakhurst?adjust_creative=TO1fKtEL34_ZeUgitrVpAQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TO1fKtEL34_ZeUgitrVpAQ\",\n"
    		+ "	    \"review_count\": 218,\n"
    		+ "	    \"categories\": [\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"newamerican\",\n"
    		+ "	            \"title\": \"American (New)\"\n"
    		+ "	        },\n"
    		+ "	        {\n"
    		+ "	            \"alias\": \"lounges\",\n"
    		+ "	            \"title\": \"Lounges\"\n"
    		+ "	        }\n"
    		+ "	    ],\n"
    		+ "	    \"rating\": 4.0,\n"
    		+ "	    \"coordinates\": {\n"
    		+ "	        \"latitude\": 37.3360280886114,\n"
    		+ "	        \"longitude\": -119.646133705974\n"
    		+ "	    },\n"
    		+ "	    \"transactions\": [],\n"
    		+ "	    \"price\": \"$$\",\n"
    		+ "	    \"location\": {\n"
    		+ "	        \"address1\": \"40530 Hwy 41\",\n"
    		+ "	        \"address2\": \"\",\n"
    		+ "	        \"address3\": \"\",\n"
    		+ "	        \"city\": \"Oakhurst\",\n"
    		+ "	        \"zip_code\": \"93644\",\n"
    		+ "	        \"country\": \"US\",\n"
    		+ "	        \"state\": \"CA\",\n"
    		+ "	        \"display_address\": [\n"
    		+ "	            \"40530 Hwy 41\",\n"
    		+ "	            \"Oakhurst, CA 93644\"\n"
    		+ "	        ]\n"
    		+ "	    },\n"
    		+ "	    \"phone\": \"+15596412477\",\n"
    		+ "	    \"display_phone\": \"(559) 641-2477\",\n"
    		+ "	    \"distance\": 31050.96588023089\n"
    		+ "	}\n"
    		+ "]";
}
